import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Vazirmatn } from "next/font/google";
import "./globals.css";
import ThemeProvider from "./features/theme/provider/theme-provider";
import { Card } from "@/components/ui/card";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const vazirmatn = Vazirmatn({
  variable: "--font-vazirmatn",
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${vazirmatn.variable} ${roboto.variable} flex flex-1 items-center justify-center p-4`}>
        <Card className="w-full max-w-md p-10">
          <ThemeProvider>{children}</ThemeProvider>
        </Card>
      </body>
    </html>
  );
}
