import type { Metadata } from "next";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { setRequestLocale } from "next-intl/server";
import { Roboto, Vazirmatn } from "next/font/google";

import { Card } from "@/components/ui/card";
import { Locale, localeConfigs } from "@/i18n/local";

import ThemeProvider from "../features/theme/provider/theme-provider";

import "../globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const vazirmatn = Vazirmatn({
  variable: "--font-vazirmatn",
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: Props) {
  const { locale: incomingLocale } = await params;

  if (!routing.locales.includes(incomingLocale as Locale)) {
    notFound();
  }

  const locale = incomingLocale as Locale;

  setRequestLocale(locale);

  const direction = localeConfigs[locale].dir;

  return (
    <html
      lang={locale}
      dir={direction}
    >
      <body className={`${vazirmatn.variable} ${roboto.variable} flex flex-1 items-center justify-center p-4`}>
        <Card className="w-full max-w-md p-10">
          <ThemeProvider>{children}</ThemeProvider>
        </Card>
      </body>
    </html>
  );
}
