import type { Metadata } from "next";
import { routing } from "@/i18n/routing";
import { Roboto, Vazirmatn } from "next/font/google";
import { NextIntlClientProvider, hasLocale } from "next-intl";

import { Card } from "@/components/ui/card";

import ThemeProvider from "../features/theme/provider/theme-provider";

import "../globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const vazirmatn = Vazirmatn({
  variable: "--font-vazirmatn",
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    console.log("ss");
  }
  return (
    <html lang="en">
      <body className={`${vazirmatn.variable} ${roboto.variable} flex flex-1 items-center justify-center p-4`}>
        <Card className="w-full max-w-md p-10">
          <NextIntlClientProvider>
            <ThemeProvider>{children}</ThemeProvider>
          </NextIntlClientProvider>
        </Card>
      </body>
    </html>
  );
}
