import { ReactNode } from "react";
import type { Metadata } from "next";
import { Roboto, Vazirmatn } from "next/font/google";

import { Card } from "@/components/ui/card";
import { I18nProviderClient } from "@/locales/client";

import HeaderTop from "../features/header/components/header-top";
import ThemeProvider from "../features/theme/provider/theme-provider";

import "../globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const vazirmatn = Vazirmatn({
  variable: "--font-vazirmatn",
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: { children: ReactNode; params: Promise<{ locale: string }> }) {
  const { locale } = await params;

  return (
    <html
      lang={locale}
      dir={locale === "fa" ? "rtl" : "ltr"}
    >
      <body className={`${vazirmatn.variable} ${roboto.variable} flex flex-1 items-center justify-center p-4`}>
        <Card className="w-full max-w-md gap-0 p-10">
          <I18nProviderClient locale={locale}>
            <ThemeProvider>
              <HeaderTop />
              {children}
            </ThemeProvider>
          </I18nProviderClient>
        </Card>
      </body>
    </html>
  );
}
